### ISSUE TITLE
[Bug]: #1 is still present on 1.19.2

### ISSUE THREAD

**Issue by Sshmoob** [Mrbysco/5head#2]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.5

### Mod version

2.0.1

### Java version

Java 17

### Issue Description

#1 Also occurs on 1.19.2, and wasn't fixed when that issue was fixed on 1.20.

### Additional Information

![image](https://github.com/Mrbysco/5head/assets/80718549/b5e9be33-67f2-4794-bb64-e4dfac3ea1ea)
Here's the resulting head's nbt data:
minecraft:player_head{SkullOwner: {Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTRjN2Q5MTM2MTJlZjBhODllMzVmZDc1MDEzNjIyYTQyZjg0ZGEyYzhmYzc4YWMxOWJkMDI5YmViMWExZWQ5MiIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjlhNzY1Mzc2NDc5ODlmOWEwYjZkMDAxZTMyMGRhYzU5MWMzNTllOWU2MWEzMWY0Y2UxMWM4OGYyMDdmMGFkNCIKICAgIH0KICB9Cn0="}]}, Id: [I; -1, -1492768929, -1, -1492768929]}, display: {Name: '{"text":"StormDragon_64\'s Head"}'}, FiveHeadScale: 0.0f}

**Comment by Mrbysco** [comment]
Backported the fix
